### ISSUE TITLE
Initial device research

### ISSUE THREAD

**Issue by wdoug** [codefordenver/shelter-availability#17]
What are different possibilities around cost and practicality for a device to capture bed data.

**Comment by fredmon3** [comment]
Raspberry Pi 3 is ~$30 with built in wifi and bluetooth.  Writing a very small python script to go full screen with a webkit webview and display a website is fairly straightforward.  This could connect over HDMI to a display or the RPi touchscreen.  We can also add hardware buttons that can hook into javascript callback functions in the displayed site, decreasing code duplication.  If pure touchscreen is desired, kindle fires are probably the cheapest devices with touchscreens that we could use.
